### ISSUE TITLE
model file?

### ISSUE THREAD

**Issue by mnuriyumusak** [md-121/yellow-sticky-traps-detection#1]
i very good study. appreciate it. i want to try it but i could not find the model checkpoint file.

**Comment by mnuriyumusak** [comment]
any improvement?

**Comment by md-121** [comment]
Hey Mehmet,
thank you for your interest.
I just uploaded the model checkpoints here https://zenodo.org/records/10403044.
The link is also available in the readme file.

**Comment by mnuriyumusak** [comment]
thanks a lot
